---

- name: Debug | uri
  ansible.builtin.debug:
    msg: "https://api.crxcavator.io/v1/report/{{ item }}/"
  # loop: "{{ chrome_extensions + chrome_extension_whitelist + chrome_extension_force }}"
  loop:
    - cjpalhdlnbpafiamejdnhcphjbkeiagm

- name: Retrieve data from crxcavator
  ansible.builtin.uri:
    url: "https://api.crxcavator.io/v1/report/{{ item }}/"
    return_content: true
  register: extreports
  # loop: "{{ chrome_extensions + chrome_extension_whitelist + chrome_extension_force }}"
  loop:
    - cjpalhdlnbpafiamejdnhcphjbkeiagm

# jq -r '.[-1] | [.data.webstore.name, .extension_id, .data.webstore.rating, .data.risk.csp.total, .data.risk.permissions.total, .data.risk.webstore.total]'
- name: Crxcavator extensions results
  ansible.builtin.debug:
    var: item
  loop: "{{ extreports.content | community.general.json_query('[-1:].[data.webstore.name, data.extension_id, data.webstore.rating, data.risk.csp.total, data.risk.permissions.total, data.risk.webstore.total]') }}"
