---

- name: Macos | Ensure Managed preferences directory exists
  ansible.builtin.file:
    dest: "/Library/Managed Preferences"
    mode: '0755'
    state: directory

- name: Macos | Set Global policies
  ansible.builtin.template:
    src: "{{ chrome_policies_template_macos }}.j2"
    dest: "/Library/Managed Preferences/com.google.Chrome.plist"
    mode: '0644'
  notify:
    - Plist binary conversion
